name: Nicotb Project Document
theme: minima
markdown: kramdown
github_username: johnjohnlin
title: "Nicotb document"
description: "A tiny framework for Python-SystemVerilog co-sumulation"
author: "Yu Sheng Lin"
header_pages:
 - index.html
